version: '2.1'

services:
  blog:
    image: fmblancokairos/blog-microservice
    links: 
      - "db"
      - "swearing"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db/blog
      SWEARING_MICROSERVICE_URL: swearing:8081
    ports:
      - "8443:8443"
    depends_on:
      db:
        condition: service_healthy

  swearing:
    image: fmblancokairos/swearing

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: admin_blog
      MYSQL_PASSWORD: admin_blog
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10