apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: fmblancokairos/blog-microservice
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://db/blog
        - name: SWEARING_MICROSERVICE_URL
          value: swearing:8081
        ports:
          - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: blog
  labels:
    app: blog
spec:
  ports:
  - port: 8443
    nodePort: 30000
  selector:
    app: blog
  type: NodePort